FROM node:20-alpine3.18

WORKDIR /app

COPY package.json package-lock.json ./

# Безопасная установка
RUN npm install --ignore-scripts --no-audit --no-fund

COPY . .

EXPOSE 5000

# Меняем владельца файлов
RUN chown -R node:node /app

# Переключаемся на непривилегированного пользователя
USER node

CMD ["npm", "run", "start:dev"]